services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - api-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-api-default:5432/meu_projeto
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha_forte

networks:
  api-network:
    external: true